services:
  be:
    build:
      context: ../
      dockerfile: ./be/Dockerfile
  nginx:
    image: nginx:1.27.4-bookworm
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - be
