services:
  be:
    build:
      context: ./
      dockerfile: ./Dockerfile
  nginx:
    image: nginx:1.27.4-bookworm
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - be
